# Generated by Django 4.2.4 on 2023-09-23 20:08

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    
    # Fetching all Profile objects where uuid is None and assigning a new UUID
    for profile in Profile.objects.filter(uuid__isnull=True):
        profile.uuid = uuid.uuid4()
        profile.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
