# Generated by Django 4.2.4 on 2023-10-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0004_gladiatorus_initial_setup'),
        ('users', '0002_profile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_orientations',
            field=models.ManyToManyField(related_name='users_allowed', to='orientation.orientation'),
        ),
    ]
