# Generated by Django 4.2.4 on 2023-10-20 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magistrate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registrar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registered_tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
