# Generated by Django 4.2.4 on 2023-10-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magistrate', '0002_tournament_registrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='organization_host',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='registrar',
        ),
    ]
