# Generated by Django 4.2.4 on 2023-11-13 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('magistrate', '0004_alter_matchseries_tournament_delete_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchseries',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='team.team'),
        ),
        migrations.AlterField(
            model_name='matchseries',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='team.team'),
        ),
    ]
