# Generated by Django 4.2.4 on 2023-11-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magistrate', '0005_alter_matchseries_team1_alter_matchseries_team2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='match_series',
        ),
        migrations.DeleteModel(
            name='MatchSeries',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
