# Generated by Django 4.2.4 on 2023-10-25 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dominus', '0002_remove_organization_owner_organization_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='registrar',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registered_organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
