# Generated by Django 4.2.4 on 2023-11-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominus', '0006_organization_owner_alter_organization_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='organization',
        ),
    ]
