# Generated by Django 4.2.4 on 2023-11-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magistrate', '0005_alter_matchseries_team1_alter_matchseries_team2'),
        ('dominus', '0007_remove_team_members_remove_team_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
