# Generated by Django 4.2.4 on 2023-11-13 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dominus', '0008_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
